testing email success failues

diff --git a/Jenkinsfile-scm b/Jenkinsfile-scm
--- a/Jenkinsfile-scm
+++ b/Jenkinsfile-scm
@@ -7,7 +7,8 @@ stages {
 
 stage ('Checkout') {
 steps {
-echo "dummy step"
+echo "dummy step, failing job"
+sh "exit 1;"
 }}
 
 }
